spring:
  application:
    name: manud-jaya

  data:
    mongodb:
      uri: ${DEV_MONGODB_URI}

supabase:
  url: ${DEV_SUPABASE_URL}
  api-key: ${DEV_SUPABASE_API_KEY}
  bucket: ${DEV_SUPABASE_BUCKET:Object-Image-Dev}

  s3:
    endpoint: ${DEV_S3_ENDPOINT}
    access-key: ${DEV_S3_ACCESS_KEY}
    secret-key: ${DEV_S3_SECRET_KEY}

jwt:
  secret-key: ${DEV_JWT_SECRET}

app:
  openapi:
    server-url: https://desa-manud-jaya-backend-dev.up.railway.app

booking:
  require-assigned-guide: ${BOOKING_REQUIRE_ASSIGNED_GUIDE:true}

logging:
  level:
    root: INFO
    com.example.manud_jaya: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
